export const NOTIFIER_ACTION = Object.freeze({
    SHOW_NOTIFICATION: Symbol('SHOW_NOTIFICATION'),
    HIDE_NOTIFICATION: Symbol('HIDE_NOTIFICATION'),
    HIDE_ALL_NOTIFICATIONS: Symbol('HIDE_ALL_NOTIFICATIONS')
});
